/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Boxster.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function Boxster(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Boxster.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.005, -0.011, -1.509]}>
        <group position={[0, 0.694, 1.12]} rotation={[-1.571, 0, 0]}>
          <group position={[0.027, -0.116, -0.693]} rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 0.758, -1.743]}>
              <mesh geometry={nodes.Object_340.geometry} material={materials.Lights} />
              <mesh geometry={nodes.Object_341.geometry} material={materials['Plastic_-_Glossy_Black2']} />
            </group>
            <group position={[0, 0.762, 1.489]}>
              <mesh geometry={nodes.Body.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
              <mesh geometry={nodes.Body001.geometry} material={materials.Slaughter} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
              <mesh geometry={nodes.Body002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
              <mesh geometry={nodes.Body003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
              <mesh geometry={nodes.Body004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
              <mesh geometry={nodes.Body005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
              <mesh geometry={nodes.Body006.geometry} material={materials.SpiderID} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
              <mesh geometry={nodes.Body007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
              <mesh geometry={nodes.Body008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
              <mesh geometry={nodes.Body009.geometry} material={materials.Mayan} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
              <mesh geometry={nodes.Body010.geometry} material={materials.SeaBreeze} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
              <mesh geometry={nodes.Body011.geometry} material={materials.ShapeShifter} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
              <mesh geometry={nodes.Body012.geometry} material={materials.Silk} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
              <mesh geometry={nodes.Body013.geometry} material={materials.SnakeSkin} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
              <mesh geometry={nodes.Body014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
              <mesh geometry={nodes.Body015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
              <mesh geometry={nodes.Body016.geometry} material={materials.TopGun} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
              <mesh geometry={nodes.Body017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
              <mesh geometry={nodes.Body018.geometry} material={materials.WildWest} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
              <mesh geometry={nodes.Body019.geometry} material={materials.Zombie} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
              <mesh geometry={nodes.Mirrors.geometry} material={materials['Metal_-_Black']} />
            </group>
            <mesh geometry={nodes.Object_8.geometry} material={materials.Window_Glass} position={[0, 0.949, -1.333]} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Lights} position={[0, 0.95, -1.329]} />
            <mesh geometry={nodes.Object_212.geometry} material={materials.Lights} position={[0, 0.953, -1.327]} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Plastic_-_Matte_Red']} position={[0.001, 0.407, -0.172]} />
            <mesh geometry={nodes.Object_14.geometry} material={materials['Metal_-_Chrome']} position={[0.597, 0.589, -0.414]} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0.611, 0.613, -0.434]} />
            <mesh geometry={nodes.Object_18.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0.108, 0.417, -0.161]} />
            <mesh geometry={nodes.Object_34.geometry} material={materials['Metal_-_Chrome']} position={[0.102, 0.395, -0.187]} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.Belt} position={[0.386, 0.63, -0.214]} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Belt} position={[0.613, 0.687, -0.432]} />
            <mesh geometry={nodes.Object_36.geometry} material={materials.Belt} position={[-0.613, 0.687, -0.432]} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.Body_Detail} position={[-0.004, 0.712, -2.081]} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.Body_Detail} position={[0.005, 0.777, -2.066]} />
            <mesh geometry={nodes.Object_180.geometry} material={materials.Body_Detail} position={[0, 0.65, 1.996]} />
            <mesh geometry={nodes.Object_28.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.072, 0.819, 0.283]} />
            <mesh geometry={nodes.Object_30.geometry} material={materials.Carpet} position={[0.013, 0.453, 0.24]} />
            <mesh geometry={nodes.Object_32.geometry} material={materials['Metal_-_Chrome']} position={[0.021, 0.538, 0.016]} />
            <mesh geometry={nodes.Object_38.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.46, 0.253]} />
            <mesh geometry={nodes.Object_40.geometry} material={materials.Bottom_Carriage} position={[-0.682, 0.343, 1.217]} />
            <mesh geometry={nodes.Object_42.geometry} material={materials.Bottom_Carriage} position={[0.684, 0.352, -1.218]} />
            <mesh geometry={nodes.Object_44.geometry} material={materials.Bottom_Carriage} position={[0.682, 0.343, 1.217]} />
            <mesh geometry={nodes.Object_182.geometry} material={materials.Bottom_Carriage} position={[-0.684, 0.352, -1.218]} />
            <mesh geometry={nodes.Object_46.geometry} material={materials['Leather_-_Black']} position={[0.035, 0.885, 0.109]} />
            <mesh geometry={nodes.Object_48.geometry} material={materials.Leather} position={[0.034, 0.653, 0.457]} />
            <mesh geometry={nodes.Object_50.geometry} material={materials['Metal_-_Chrome']} position={[0.667, 0.653, 0.234]} />
            <mesh geometry={nodes.Object_52.geometry} material={materials['Metal_-_Chrome']} position={[0.008, 0.663, 0.294]} />
            <mesh geometry={nodes.Object_54.geometry} material={materials['Metal_-_Chrome']} position={[0.664, 0.774, 0.019]} />
            <mesh geometry={nodes.Object_56.geometry} material={materials['Metal_-_Chrome']} position={[-0.664, 0.644, 0.2]} />
            <mesh geometry={nodes.Object_184.geometry} material={materials['Metal_-_Chrome']} position={[-0.664, 0.774, 0.019]} />
            <mesh geometry={nodes.Object_58.geometry} material={materials.Window_Glass} position={[0.29, 0.838, 0.485]} />
            <mesh geometry={nodes.Object_60.geometry} material={materials.Body_Detail} position={[0.511, 0.867, 0.855]} />
            <mesh geometry={nodes.Object_62.geometry} material={materials.Dials} position={[0.372, 0.822, 0.49]} />
            <mesh geometry={nodes.Object_64.geometry} material={materials.Dials} position={[0.222, 0.85, 0.561]} />
            <mesh geometry={nodes.Object_66.geometry} material={materials.material} position={[0.382, 0.79, 0.485]} />
            <mesh geometry={nodes.Object_68.geometry} material={materials.Interior_Detail} position={[0.334, 0.821, 0.486]} />
            <mesh geometry={nodes.Object_70.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.265, 0.848, 0.5]} />
            <mesh geometry={nodes.Object_72.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.232, 0.85, 0.5]} />
            <mesh geometry={nodes.Object_74.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.235, 0.851, 0.5]} />
            <mesh geometry={nodes.Object_76.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.23, 0.848, 0.499]} />
            <mesh geometry={nodes.Object_78.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.242, 0.852, 0.501]} />
            <mesh geometry={nodes.Object_80.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.245, 0.853, 0.501]} />
            <mesh geometry={nodes.Object_82.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.247, 0.852, 0.501]} />
            <mesh geometry={nodes.Object_84.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.25, 0.853, 0.501]} />
            <mesh geometry={nodes.Object_86.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.253, 0.852, 0.501]} />
            <mesh geometry={nodes.Object_88.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.256, 0.852, 0.5]} />
            <mesh geometry={nodes.Object_90.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.26, 0.851, 0.5]} />
            <mesh geometry={nodes.Object_92.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.263, 0.85, 0.5]} />
            <mesh geometry={nodes.Object_94.geometry} material={materials.Dials} position={[0.423, 0.801, 0.487]} />
            <mesh geometry={nodes.Object_96.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0.436, 0.801, 0.485]} />
            <mesh geometry={nodes.Object_98.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0.423, 0.815, 0.488]} />
            <mesh geometry={nodes.Object_100.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0.354, 0.822, 0.485]} />
            <mesh geometry={nodes.Object_102.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0.336, 0.837, 0.489]} />
            <mesh geometry={nodes.Object_104.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.21, 0.848, 0.568]} />
            <mesh geometry={nodes.Object_106.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.238, 0.852, 0.5]} />
            <mesh geometry={nodes.Object_108.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.259, 0.798, 0.487]} />
            <mesh geometry={nodes.Object_110.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.245, 0.817, 0.492]} />
            <mesh geometry={nodes.Object_112.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.252, 0.817, 0.492]} />
            <mesh geometry={nodes.Object_114.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.259, 0.817, 0.492]} />
            <mesh geometry={nodes.Object_116.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.237, 0.807, 0.49]} />
            <mesh geometry={nodes.Object_118.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.245, 0.807, 0.49]} />
            <mesh geometry={nodes.Object_120.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.252, 0.807, 0.49]} />
            <mesh geometry={nodes.Object_122.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.259, 0.807, 0.49]} />
            <mesh geometry={nodes.Object_124.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.237, 0.798, 0.487]} />
            <mesh geometry={nodes.Object_126.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.245, 0.798, 0.487]} />
            <mesh geometry={nodes.Object_128.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.252, 0.798, 0.487]} />
            <mesh geometry={nodes.Object_130.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.261, 0.826, 0.494]} />
            <mesh geometry={nodes.Object_132.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.257, 0.826, 0.494]} />
            <mesh geometry={nodes.Object_134.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.253, 0.826, 0.494]} />
            <mesh geometry={nodes.Object_136.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.25, 0.826, 0.494]} />
            <mesh geometry={nodes.Object_138.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.246, 0.826, 0.494]} />
            <mesh geometry={nodes.Object_140.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.243, 0.826, 0.494]} />
            <mesh geometry={nodes.Object_142.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.239, 0.826, 0.494]} />
            <mesh geometry={nodes.Object_144.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.235, 0.826, 0.494]} />
            <mesh geometry={nodes.Object_146.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0, 0.896, 0.664]} />
            <mesh geometry={nodes.Object_148.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0, 0.886, 0.661]} />
            <mesh geometry={nodes.Object_150.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0, 0.872, 0.655]} />
            <mesh geometry={nodes.Object_152.geometry} material={materials['Interior_Detail_-_Plastic']} position={[0, 0.874, 0.657]} />
            <mesh geometry={nodes.Object_332.geometry} material={materials.INT_DETAILS_Emissive_Ref} position={[0.237, 0.817, 0.492]} />
            <mesh geometry={nodes.Object_154.geometry} material={materials['Interior_Detail_-_Emissive']} position={[0.084, 0.759, 0.435]} />
            <mesh geometry={nodes.Object_156.geometry} material={materials['Body_Paint_-_Miami_Blue']} position={[0, 0.539, 0.234]} />
            <mesh geometry={nodes.Object_158.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.299, -2.066]} />
            <mesh geometry={nodes.Object_160.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.761, -0.671]} />
            <mesh geometry={nodes.Object_164.geometry} material={materials.Body_Detail} position={[0, 0.475, 2.105]} />
            <mesh geometry={nodes.Object_166.geometry} material={materials.Window_Glass} position={[0, 0.443, 2.046]} />
            <mesh geometry={nodes.Object_168.geometry} material={materials.Lights} position={[0, 0.444, 2.036]} />
            <mesh geometry={nodes.Object_208.geometry} material={materials.Lights} position={[-0.001, 0.444, 2.038]} />
            <mesh geometry={nodes.Object_170.geometry} material={materials['Plastic_-_Matte_Black']} position={[0.001, 0.616, 0.259]} />
            <mesh geometry={nodes.Object_172.geometry} material={materials['Metal_-_Chrome']} position={[0.001, 0.61, 0.258]} />
            <mesh geometry={nodes.Object_174.geometry} material={materials['Metal_-_Chrome']} position={[0, 0.575, 0.181]} />
            <mesh geometry={nodes.Object_176.geometry} material={materials.Interior_Detail} position={[0.244, 0.712, 0.225]} />
            <mesh geometry={nodes.Object_206.geometry} material={materials.Interior_Detail} position={[-0.007, 0.584, 0.257]} />
            <mesh geometry={nodes.Object_178.geometry} material={materials.Exhaust} position={[0, 0.25, -2.087]} />
            <mesh geometry={nodes.Object_188.geometry} material={materials.Interior_Grid} position={[0, 1.07, -0.655]} />
            <mesh geometry={nodes.Object_186.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.327, 2.07]} />
            <mesh geometry={nodes.Object_190.geometry} material={materials['Plastic_-_Glossy_Black2']} position={[0, 0.692, 1.721]} />
            <mesh geometry={nodes.Object_192.geometry} material={materials['Metal_-_Chrome']} position={[0, 0.703, 1.709]} />
            <mesh geometry={nodes.Object_194.geometry} material={materials.Lights} position={[0, 0.692, 1.731]} />
            <mesh geometry={nodes.Object_196.geometry} material={materials['Lights_-Chrome']} position={[0, 0.685, 1.718]} />
            <mesh geometry={nodes.Object_210.geometry} material={materials.Lights} position={[0, 0.76, 1.574]} />
            <mesh geometry={nodes.Object_198.geometry} material={materials.Window_Glass} position={[0, 0.706, 1.737]} />
            <mesh geometry={nodes.Object_200.geometry} material={materials.Bottom_Carriage} position={[0, 0.594, 1.931]} />
            <mesh geometry={nodes.Object_204.geometry} material={materials.EXT_Ind_Light} position={[0.008, 0.604, 1.566]} />
            <mesh geometry={nodes.Object_216.geometry} material={materials['Body_Paint_-_Miami_Blue']} position={[0.795, 0.555, 0.356]} />
            <mesh geometry={nodes.Object_218.geometry} material={materials.Rubber} position={[0.786, 0.681, -0.066]} />
            <mesh geometry={nodes.Object_220.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.832, 0.865, 0.346]} />
            <mesh geometry={nodes.Object_222.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.689, 0.762, 0.375]} />
            <mesh geometry={nodes.Object_224.geometry} material={materials.Leather} position={[0.672, 0.844, -0.02]} />
            <mesh geometry={nodes.Object_226.geometry} material={materials.Leather} position={[0.666, 0.637, 0.133]} />
            <mesh geometry={nodes.Object_228.geometry} material={materials['Plastic_-_Matte_Black']} position={[0.666, 0.565, 0.217]} />
            <mesh geometry={nodes.Object_230.geometry} material={materials.Carpet} position={[0.671, 0.499, -0.006]} />
            <mesh geometry={nodes.Object_232.geometry} material={materials.Interior_Detail} position={[0.674, 0.692, 0.315]} />
            <mesh geometry={nodes.Object_234.geometry} material={materials.Stich} position={[0.655, 0.7, -0.012]} />
            <mesh geometry={nodes.Object_236.geometry} material={materials.Mirror} position={[-0.897, 0.914, 0.287]} />
            <mesh geometry={nodes.Object_240.geometry} material={materials.Mirror} position={[0, 1.11, 0.28]} />
            <mesh geometry={nodes.Object_238.geometry} material={materials.Mirror} position={[0.897, 0.914, 0.287]} />
            <mesh geometry={nodes.Object_242.geometry} material={materials['Plastic_-_Glossy_Black2']} position={[0, 0.537, -2.079]} />
            <mesh geometry={nodes.Object_244.geometry} material={materials.Lights} position={[0, 0.43, -1.914]} />
            <mesh geometry={nodes.Object_248.geometry} material={materials.Body_Detail} position={[0, 0.47, -2.055]} />
            <mesh geometry={nodes.Object_252.geometry} material={materials['Body_Paint_-_Miami_Blue']} position={[-0.795, 0.555, 0.356]} />
            <mesh geometry={nodes.Object_254.geometry} material={materials.Rubber} position={[-0.786, 0.681, -0.066]} />
            <mesh geometry={nodes.Object_256.geometry} material={materials['Plastic_-_Glossy_Black']} position={[-0.831, 0.863, 0.348]} />
            <mesh geometry={nodes.Object_258.geometry} material={materials['Plastic_-_Glossy_Black']} position={[-0.694, 0.785, 0.394]} />
            <mesh geometry={nodes.Object_260.geometry} material={materials.Leather} position={[-0.672, 0.844, -0.02]} />
            <mesh geometry={nodes.Object_262.geometry} material={materials.Leather} position={[-0.666, 0.637, 0.133]} />
            <mesh geometry={nodes.Object_264.geometry} material={materials['Plastic_-_Matte_Black']} position={[-0.666, 0.562, 0.215]} />
            <mesh geometry={nodes.Object_266.geometry} material={materials.Carpet} position={[-0.671, 0.499, -0.006]} />
            <mesh geometry={nodes.Object_268.geometry} material={materials.Interior_Detail} position={[-0.683, 0.737, 0.338]} />
            <mesh geometry={nodes.Object_270.geometry} material={materials.Stich} position={[-0.655, 0.7, -0.012]} />
            <mesh geometry={nodes.Object_272.geometry} material={materials['Plastic_-_Matte_Black']} position={[0.001, 1.032, -0.683]} />
            <mesh geometry={nodes.Object_274.geometry} material={materials.Roof} position={[0, 0.932, -0.943]} />
            <mesh geometry={nodes.Object_278.geometry} material={materials.Leather} position={[-0.001, 0.567, -0.271]} />
            <mesh geometry={nodes.Object_276.geometry} material={materials.Leather} position={[0, 0.457, -0.184]} />
            <mesh geometry={nodes.Object_280.geometry} material={materials.Interior_Detail} position={[0, 0.482, -0.031]} />
            <mesh geometry={nodes.Object_284.geometry} material={materials.Interior_Detail} position={[0.104, 0.696, 0.348]} />
            <mesh geometry={nodes.Object_286.geometry} material={materials.Interior_Detail} position={[0.244, 0.512, 0.58]} />
            <mesh geometry={nodes.Object_288.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.193, 0.664, 0.335]} />
            <mesh geometry={nodes.Object_290.geometry} material={materials.Rubber} position={[0.302, 0.416, 0.772]} />
            <mesh geometry={nodes.Object_282.geometry} material={materials.Rubber} position={[0.008, 0.854, 0.15]} />
            <mesh geometry={nodes.Object_294.geometry} material={materials.Speaker} position={[0.662, 0.556, 0.348]} />
            <mesh geometry={nodes.Object_296.geometry} material={materials.Speaker} position={[0, 0.666, 0.362]} />
            <mesh geometry={nodes.Object_292.geometry} material={materials.Speaker} position={[-0.662, 0.556, 0.348]} />
            <mesh geometry={nodes.Object_300.geometry} material={materials['Plastic_-_Glossy_Black2']} position={[0, 0.767, -1.98]} />
            <mesh geometry={nodes.Object_302.geometry} material={materials.Bottom_Carriage} position={[0, 0.752, -1.942]} />
            <mesh geometry={nodes.Object_304.geometry} material={materials.Bottom_Carriage} position={[0, 0.709, -1.933]} />
            <mesh geometry={nodes.Object_306.geometry} material={materials.Bottom_Carriage} position={[0, 0.701, -1.931]} />
            <mesh geometry={nodes.Object_308.geometry} material={materials.Bottom_Carriage} position={[0, 0.73, -1.964]} />
            <mesh geometry={nodes.Object_298.geometry} material={materials['Metal_-_Black']} position={[0, 0.792, -1.964]} />
            <mesh geometry={nodes.Object_312.geometry} material={materials['Leather_-_Dark']} position={[0.335, 0.785, 0.238]} />
            <mesh geometry={nodes.Object_314.geometry} material={materials['Metal_-_Chrome']} position={[0.335, 0.753, 0.239]} />
            <mesh geometry={nodes.Object_316.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.296, 0.739, 0.249]} />
            <mesh geometry={nodes.Object_318.geometry} material={materials.Interior_Detail} position={[0.321, 0.761, 0.233]} />
            <mesh geometry={nodes.Object_310.geometry} material={materials.Stich} position={[0.336, 0.799, 0.247]} />
            <mesh geometry={nodes.Object_322.geometry} material={materials.Stich} position={[0.031, 0.576, -0.136]} />
            <mesh geometry={nodes.Object_320.geometry} material={materials.Stich} position={[-0.011, 0.683, 0.315]} />
            <mesh geometry={nodes.Object_326.geometry} material={materials.Bottom_Carriage} position={[-0.003, 0.429, -0.84]} />
            <mesh geometry={nodes.Object_328.geometry} material={materials.Bottom_Carriage} position={[0, 0.352, 1.991]} />
            <mesh geometry={nodes.Object_330.geometry} material={materials.Bottom_Carriage} position={[0, 0.555, -1.858]} />
            <mesh geometry={nodes.Object_324.geometry} material={materials.Bottom_Carriage} position={[0, 0.778, 1.372]} />
            <mesh geometry={nodes.Object_336.geometry} material={materials['Plastic_-_Matte_Black']} position={[0.585, 0.72, 0.399]} />
            <mesh geometry={nodes.Object_338.geometry} material={materials.Interior_Detail} position={[0.585, 0.721, 0.393]} />
            <mesh geometry={nodes.Object_334.geometry} material={materials['Metal_-_Chrome']} position={[0.585, 0.719, 0.393]} />
            <mesh geometry={nodes.Object_343.geometry} material={materials.Window_Glass} position={[0, 0.758, -1.783]} />
            <mesh geometry={nodes.Object_347.geometry} material={materials.Lights} position={[0, 0.762, -1.791]} />
            <mesh geometry={nodes.Object_349.geometry} material={materials.Lights} position={[0, 0.761, -1.781]} />
            <mesh geometry={nodes.Object_345.geometry} material={materials['Lights_-Chrome']} position={[0, 0.757, -1.745]} />
            <mesh geometry={nodes.Object_355.geometry} material={materials['Plastic_-_Matte_Black']} position={[0.023, 0.831, 0.39]} />
            <mesh geometry={nodes.Object_353.geometry} material={materials.Window_Glass_not_transparent} position={[0, 1.088, 0.393]} />
            <mesh geometry={nodes.Object_357.geometry} material={materials.Window_Glass} position={[0.661, 1.037, -0.099]} />
            <mesh geometry={nodes.Object_359.geometry} material={materials.Window_Glass} position={[-0.661, 1.037, -0.099]} />
            <mesh geometry={nodes.Object_351.geometry} material={materials.Window_Glass} position={[0, 1.054, 0.498]} />
            <mesh geometry={nodes.Object_363.geometry} material={materials['Metal_-_Black']} position={[-0.412, 0.883, 0.82]} />
            <mesh geometry={nodes.Object_365.geometry} material={materials['Metal_-_Black']} position={[0.171, 0.89, 0.89]} />
            <mesh geometry={nodes.Object_367.geometry} material={materials['Metal_-_Black']} position={[0.423, 0.87, 0.87]} />
            <mesh geometry={nodes.Object_369.geometry} material={materials.Body_Detail} position={[-0.087, 0.729, 0.986]} />
            <mesh geometry={nodes.Object_361.geometry} material={materials['Metal_-_Black']} position={[-0.149, 0.876, 0.95]} />
          </group>
        </group>
        <group position={[0.817, 0.351, 0]} rotation={[-1.571, 0, 0]}>
          <group position={[-0.79, -1.237, -0.351]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_394.geometry} material={materials.Tyre} />
            <mesh geometry={nodes.Object_396.geometry} material={materials.Body_Detail} position={[0.811, 0.385, -1.116]} />
            <mesh geometry={nodes.Object_400.geometry} material={materials.EXT_DETAILS} position={[0.857, 0.351, -1.237]} />
            <mesh geometry={nodes.Object_398.geometry} material={materials.material_34} position={[0.863, 0.35, -1.239]} />
            <mesh geometry={nodes.Object_402.geometry} material={materials.Rotor} position={[0.764, 0.351, -1.237]} />
          </group>
        </group>
        <group position={[-0.764, 0.351, 0]} rotation={[-1.571, 0, 0]}>
          <group position={[0.79, -1.237, -0.351]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_405.geometry} material={materials.Tyre} />
            <mesh geometry={nodes.Object_407.geometry} material={materials.Body_Detail} position={[-0.812, 0.385, -1.116]} />
            <mesh geometry={nodes.Object_409.geometry} material={materials.EXT_DETAILS} position={[-0.857, 0.351, -1.237]} />
            <mesh geometry={nodes.Object_411.geometry} material={materials.material_34} position={[-0.863, 0.35, -1.239]} />
            <mesh geometry={nodes.Object_413.geometry} material={materials.Rotor} position={[-0.764, 0.351, -1.237]} />
          </group>
        </group>
        <group position={[0.817, 0.346, 2.474]} rotation={[-1.571, 0, 0]}>
          <group position={[-0.79, 1.237, -0.345]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_372.geometry} material={materials.Tyre} />
            <mesh geometry={nodes.Object_374.geometry} material={materials.Body_Detail} position={[0.818, 0.368, 1.093]} />
            <mesh geometry={nodes.Object_376.geometry} material={materials.EXT_DETAILS} position={[0.857, 0.345, 1.237]} />
            <mesh geometry={nodes.Object_378.geometry} material={materials.material_34} position={[0.863, 0.343, 1.236]} />
            <mesh geometry={nodes.Object_380.geometry} material={materials.Rotor} position={[0.761, 0.341, 1.237]} />
          </group>
        </group>
        <group position={[-0.764, 0.346, 2.474]} rotation={[-1.571, 0, 0]}>
          <group position={[0.79, 1.237, -0.345]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_383.geometry} material={materials.Tyre} />
            <mesh geometry={nodes.Object_385.geometry} material={materials.Body_Detail} position={[-0.818, 0.369, 1.092]} />
            <mesh geometry={nodes.Object_387.geometry} material={materials.EXT_DETAILS} position={[-0.857, 0.345, 1.237]} />
            <mesh geometry={nodes.Object_389.geometry} material={materials.material_34} position={[-0.863, 0.343, 1.236]} />
            <mesh geometry={nodes.Object_391.geometry} material={materials.Rotor} position={[-0.761, 0.341, 1.237]} />
          </group>
        </group>
        <group position={[0.79, 0.379, 0.123]} rotation={[-1.571, 0, 0]}>
          <mesh geometry={nodes.Object_422.geometry} material={materials.Caliper} position={[-0.763, -1.114, -0.379]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-0.736, 0.379, 0.123]} rotation={[-1.571, 0, 0]}>
          <mesh geometry={nodes.Object_425.geometry} material={materials.Caliper} position={[0.763, -1.114, -0.379]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[0.8, 0.364, 2.323]} rotation={[-1.571, 0, 0]}>
          <mesh geometry={nodes.Object_416.geometry} material={materials.Caliper} position={[-0.773, 1.086, -0.363]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-0.746, 0.364, 2.323]} rotation={[-1.571, 0, 0]}>
          <mesh geometry={nodes.Object_419.geometry} material={materials.Caliper} position={[0.773, 1.086, -0.363]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Boxster.glb')
